### ISSUE TITLE
Fix Windows CI

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/Swifty-LLVM#15]
I had to disable Windows CI because I got failures trying to compile some shims for the LLVM C API. The problem appears to be that we should manually specify what libraries to link in `Package.swift`. See https://github.com/val-lang/Swifty-LLVM/actions/runs/4873453734

@C-BJ, maybe you'd like to take a look?

**Comment by C-BJ** [comment]
OK

**Comment by kyouko-taiga** [comment]
Had to disable Windows CI again. See https://github.com/val-lang/Swifty-LLVM/actions/runs/5437320662/jobs/9887843023

**Comment by dabrahams** [comment]
Latest problem is:

```
Run xcopy c:\llvm-15.0.6-windows-x86-msvc17-msvcrt\include\*.* c:\program" "files\microsoft" "visual" "studio\2022\enterprise\vc\tools\msvc\14.34.31933\include /s /h
Does C:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.34.31933\include specify a file name
or directory name on the target
(F = file, D = directory)? 
Does C:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.34.31933\include specify a file name
or directory name on the target
(F = file, D = directory)? 
Error: Process completed with exit code 1.
```

**Comment by C-BJ** [comment]
I will fix it. And if you run into problems again, please @C-BJ . Or I'll miss it

**Comment by C-BJ** [comment]
@kyouko-taiga this issue should be closed

**Comment by kyouko-taiga** [comment]
Thanks!

Please don't @-me on every issue and PR. I watch the all repos in the organization so I will get notified anyway.
