### ISSUE TITLE
Test faild on windows

### ISSUE THREAD

**Issue by C-BJ** [val-lang/Swifty-LLVM#8]
This seems to be a problem with my configuration, but I have no idea because I haven't had much contact with LLVM.
So what I've added to README about Windows is probably not comprehensive enough.
```
C:\Users\19454\Desktop\Swifty-LLVM [main ≡]> swift test
warning: failed to retrieve search paths with pkg-config; maybe pkg-config is not installed
warning: couldn't find pc file for llvm
Building for debugging...
lld-link: error: could not open 'llvmc.lib': no such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[6/7] Linking C:\Users\19454\Desktop\Swifty-LLVM\.build\x86_64-unknown-windows-msvc\debug\Swifty-LLVMPackageTests.xctest
error: fatalError
```

CI for Windows: https://github.com/C-BJ/Swifty-LLVM/actions/runs/4438689100/jobs/7790088981

Could you give me some advice to try? @kyouko-taiga

**Comment by C-BJ** [comment]
Could you give me some advice to try? @kyouko-taiga

**Comment by C-BJ** [comment]
oh, I don't have c++.lib problem locally. This is my CI problem.

**Comment by C-BJ** [comment]
As for llvmc, the situation seems to be different.

**Comment by compnerd** [comment]
@C-BJ: https://github.com/C-BJ/Swifty-LLVM/blob/main/Sources/llvmc/module.modulemap#L3 It is explicitly being requested here.

I don't see any code there, so it will likely not create an import library nor a static library, and thus you get a failure to link.

**Comment by C-BJ** [comment]
So what should I do? 😶

**Comment by C-BJ** [comment]
I solved it, part of it is my LLVM problem, part of it is code problem.
I'm going to open a PR to enable Windows CI.

**Comment by C-BJ** [comment]
How do I make modulemap compile for each system condition?
@compnerd

**Comment by compnerd** [comment]
> How do I make modulemap compile for each system condition?
> 
> This is the last problem.
> 
> @compnerd @kyouko-taiga 

The module map isn't compiled - it's side car data.  As to creating a library, that's mostly the same - ensure that you have sources that define symbols.  There's a few examples in swift-tools-support-core and swift-package-manager.  I'd recommend that you just update to the upstream version as they have already fixed the issue as I pointed out earlier.

**Comment by C-BJ** [comment]
I've already done this issue locally. 
But I need Windows to have a modulemap that is independent of other systems.
I need to link a static library on Windows.
@compnerd

**Comment by C-BJ** [comment]
I solved this problem in a different way
